package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Apphasstaffvalid generated by hbm2java
 */
public class Apphasstaffvalid  implements java.io.Serializable {


     private Integer idAppHasStaffValid;
     private Application application;
     private Staff staff;
     private Date appHasStaffValidDateAndTime;
     private boolean appHasStaffValidState;

    public Apphasstaffvalid() {
    }

    public Apphasstaffvalid(Application application, Staff staff, Date appHasStaffValidDateAndTime, boolean appHasStaffValidState) {
       this.application = application;
       this.staff = staff;
       this.appHasStaffValidDateAndTime = appHasStaffValidDateAndTime;
       this.appHasStaffValidState = appHasStaffValidState;
    }
   
    public Integer getIdAppHasStaffValid() {
        return this.idAppHasStaffValid;
    }
    
    public void setIdAppHasStaffValid(Integer idAppHasStaffValid) {
        this.idAppHasStaffValid = idAppHasStaffValid;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Date getAppHasStaffValidDateAndTime() {
        return this.appHasStaffValidDateAndTime;
    }
    
    public void setAppHasStaffValidDateAndTime(Date appHasStaffValidDateAndTime) {
        this.appHasStaffValidDateAndTime = appHasStaffValidDateAndTime;
    }
    public boolean isAppHasStaffValidState() {
        return this.appHasStaffValidState;
    }
    
    public void setAppHasStaffValidState(boolean appHasStaffValidState) {
        this.appHasStaffValidState = appHasStaffValidState;
    }




}


