package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Apptype generated by hbm2java
 */
public class Apptype  implements java.io.Serializable {


     private Integer idApptype;
     private Appplatform appplatform;
     private String apptype;
     private boolean state;
     private Set<Category> categories = new HashSet<Category>(0);

    public Apptype() {
    }

	
    public Apptype(Appplatform appplatform, String apptype, boolean state) {
        this.appplatform = appplatform;
        this.apptype = apptype;
        this.state = state;
    }
    public Apptype(Appplatform appplatform, String apptype, boolean state, Set<Category> categories) {
       this.appplatform = appplatform;
       this.apptype = apptype;
       this.state = state;
       this.categories = categories;
    }
   
    public Integer getIdApptype() {
        return this.idApptype;
    }
    
    public void setIdApptype(Integer idApptype) {
        this.idApptype = idApptype;
    }
    public Appplatform getAppplatform() {
        return this.appplatform;
    }
    
    public void setAppplatform(Appplatform appplatform) {
        this.appplatform = appplatform;
    }
    public String getApptype() {
        return this.apptype;
    }
    
    public void setApptype(String apptype) {
        this.apptype = apptype;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }




}


