package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer idCity;
     private Discrict discrict;
     private String cityName;
     private boolean state;
     private Set<Developer> developers = new HashSet<Developer>(0);
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Customer> customers = new HashSet<Customer>(0);

    public City() {
    }

	
    public City(Discrict discrict, boolean state) {
        this.discrict = discrict;
        this.state = state;
    }
    public City(Discrict discrict, String cityName, boolean state, Set<Developer> developers, Set<Staff> staffs, Set<Customer> customers) {
       this.discrict = discrict;
       this.cityName = cityName;
       this.state = state;
       this.developers = developers;
       this.staffs = staffs;
       this.customers = customers;
    }
   
    public Integer getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Integer idCity) {
        this.idCity = idCity;
    }
    public Discrict getDiscrict() {
        return this.discrict;
    }
    
    public void setDiscrict(Discrict discrict) {
        this.discrict = discrict;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Developer> getDevelopers() {
        return this.developers;
    }
    
    public void setDevelopers(Set<Developer> developers) {
        this.developers = developers;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


