package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer idComment;
     private Application application;
     private String comment;
     private Date commentDateAndTime;
     private boolean state;
     private Set<Customerhascomment> customerhascomments = new HashSet<Customerhascomment>(0);
     private Set<Developerhascomment> developerhascomments = new HashSet<Developerhascomment>(0);

    public Comment() {
    }

	
    public Comment(Application application, Date commentDateAndTime, boolean state) {
        this.application = application;
        this.commentDateAndTime = commentDateAndTime;
        this.state = state;
    }
    public Comment(Application application, String comment, Date commentDateAndTime, boolean state, Set<Customerhascomment> customerhascomments, Set<Developerhascomment> developerhascomments) {
       this.application = application;
       this.comment = comment;
       this.commentDateAndTime = commentDateAndTime;
       this.state = state;
       this.customerhascomments = customerhascomments;
       this.developerhascomments = developerhascomments;
    }
   
    public Integer getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getCommentDateAndTime() {
        return this.commentDateAndTime;
    }
    
    public void setCommentDateAndTime(Date commentDateAndTime) {
        this.commentDateAndTime = commentDateAndTime;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Customerhascomment> getCustomerhascomments() {
        return this.customerhascomments;
    }
    
    public void setCustomerhascomments(Set<Customerhascomment> customerhascomments) {
        this.customerhascomments = customerhascomments;
    }
    public Set<Developerhascomment> getDeveloperhascomments() {
        return this.developerhascomments;
    }
    
    public void setDeveloperhascomments(Set<Developerhascomment> developerhascomments) {
        this.developerhascomments = developerhascomments;
    }




}


