package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customerhasapplication generated by hbm2java
 */
public class Customerhasapplication  implements java.io.Serializable {


     private Integer idCustomerHasApplication;
     private Application application;
     private Customer customer;
     private Serialkeys serialkeys;
     private Date customerHasApplicationDateAndTime;
     private Boolean isPayedDeveloper;
     private Date payedDateAndTimeToDeveloper;
     private double developerPayementPrice;
     private double incomePrice;

    public Customerhasapplication() {
    }

	
    public Customerhasapplication(Application application, Customer customer, Serialkeys serialkeys, Date customerHasApplicationDateAndTime, double developerPayementPrice, double incomePrice) {
        this.application = application;
        this.customer = customer;
        this.serialkeys = serialkeys;
        this.customerHasApplicationDateAndTime = customerHasApplicationDateAndTime;
        this.developerPayementPrice = developerPayementPrice;
        this.incomePrice = incomePrice;
    }
    public Customerhasapplication(Application application, Customer customer, Serialkeys serialkeys, Date customerHasApplicationDateAndTime, Boolean isPayedDeveloper, Date payedDateAndTimeToDeveloper, double developerPayementPrice, double incomePrice) {
       this.application = application;
       this.customer = customer;
       this.serialkeys = serialkeys;
       this.customerHasApplicationDateAndTime = customerHasApplicationDateAndTime;
       this.isPayedDeveloper = isPayedDeveloper;
       this.payedDateAndTimeToDeveloper = payedDateAndTimeToDeveloper;
       this.developerPayementPrice = developerPayementPrice;
       this.incomePrice = incomePrice;
    }
   
    public Integer getIdCustomerHasApplication() {
        return this.idCustomerHasApplication;
    }
    
    public void setIdCustomerHasApplication(Integer idCustomerHasApplication) {
        this.idCustomerHasApplication = idCustomerHasApplication;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Serialkeys getSerialkeys() {
        return this.serialkeys;
    }
    
    public void setSerialkeys(Serialkeys serialkeys) {
        this.serialkeys = serialkeys;
    }
    public Date getCustomerHasApplicationDateAndTime() {
        return this.customerHasApplicationDateAndTime;
    }
    
    public void setCustomerHasApplicationDateAndTime(Date customerHasApplicationDateAndTime) {
        this.customerHasApplicationDateAndTime = customerHasApplicationDateAndTime;
    }
    public Boolean getIsPayedDeveloper() {
        return this.isPayedDeveloper;
    }
    
    public void setIsPayedDeveloper(Boolean isPayedDeveloper) {
        this.isPayedDeveloper = isPayedDeveloper;
    }
    public Date getPayedDateAndTimeToDeveloper() {
        return this.payedDateAndTimeToDeveloper;
    }
    
    public void setPayedDateAndTimeToDeveloper(Date payedDateAndTimeToDeveloper) {
        this.payedDateAndTimeToDeveloper = payedDateAndTimeToDeveloper;
    }
    public double getDeveloperPayementPrice() {
        return this.developerPayementPrice;
    }
    
    public void setDeveloperPayementPrice(double developerPayementPrice) {
        this.developerPayementPrice = developerPayementPrice;
    }
    public double getIncomePrice() {
        return this.incomePrice;
    }
    
    public void setIncomePrice(double incomePrice) {
        this.incomePrice = incomePrice;
    }




}


