package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1



/**
 * Delopercokie generated by hbm2java
 */
public class Delopercokie  implements java.io.Serializable {


     private Integer idDeloperCokie;
     private Developer developer;
     private String deloperCokieid;

    public Delopercokie() {
    }

	
    public Delopercokie(Developer developer) {
        this.developer = developer;
    }
    public Delopercokie(Developer developer, String deloperCokieid) {
       this.developer = developer;
       this.deloperCokieid = deloperCokieid;
    }
   
    public Integer getIdDeloperCokie() {
        return this.idDeloperCokie;
    }
    
    public void setIdDeloperCokie(Integer idDeloperCokie) {
        this.idDeloperCokie = idDeloperCokie;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public String getDeloperCokieid() {
        return this.deloperCokieid;
    }
    
    public void setDeloperCokieid(String deloperCokieid) {
        this.deloperCokieid = deloperCokieid;
    }




}


