package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Developinglanguages generated by hbm2java
 */
public class Developinglanguages  implements java.io.Serializable {


     private Integer idDevelopingLanguages;
     private String developingLanguages;
     private Set<Developerhaslanguages> developerhaslanguageses = new HashSet<Developerhaslanguages>(0);

    public Developinglanguages() {
    }

    public Developinglanguages(String developingLanguages, Set<Developerhaslanguages> developerhaslanguageses) {
       this.developingLanguages = developingLanguages;
       this.developerhaslanguageses = developerhaslanguageses;
    }
   
    public Integer getIdDevelopingLanguages() {
        return this.idDevelopingLanguages;
    }
    
    public void setIdDevelopingLanguages(Integer idDevelopingLanguages) {
        this.idDevelopingLanguages = idDevelopingLanguages;
    }
    public String getDevelopingLanguages() {
        return this.developingLanguages;
    }
    
    public void setDevelopingLanguages(String developingLanguages) {
        this.developingLanguages = developingLanguages;
    }
    public Set<Developerhaslanguages> getDeveloperhaslanguageses() {
        return this.developerhaslanguageses;
    }
    
    public void setDeveloperhaslanguageses(Set<Developerhaslanguages> developerhaslanguageses) {
        this.developerhaslanguageses = developerhaslanguageses;
    }




}


