package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1



/**
 * Developerhascomment generated by hbm2java
 */
public class Developerhascomment  implements java.io.Serializable {


     private Integer idDeveloperHasComment;
     private Comment comment;
     private Developer developer;

    public Developerhascomment() {
    }

    public Developerhascomment(Comment comment, Developer developer) {
       this.comment = comment;
       this.developer = developer;
    }
   
    public Integer getIdDeveloperHasComment() {
        return this.idDeveloperHasComment;
    }
    
    public void setIdDeveloperHasComment(Integer idDeveloperHasComment) {
        this.idDeveloperHasComment = idDeveloperHasComment;
    }
    public Comment getComment() {
        return this.comment;
    }
    
    public void setComment(Comment comment) {
        this.comment = comment;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }




}


