package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Developer generated by hbm2java
 */
public class Developer  implements java.io.Serializable {


     private Integer idDeveloper;
     private City city;
     private Emailvarified emailvarified;
     private String username;
     private String developerFname;
     private String developerMname;
     private String developerLname;
     private String password;
     private String developerPhone;
     private String developerMobile;
     private String address;
     private boolean state;
     private Set<Delopercokie> delopercokies = new HashSet<Delopercokie>(0);
     private Set<Application> applications = new HashSet<Application>(0);
     private Set<Developerhaslanguages> developerhaslanguageses = new HashSet<Developerhaslanguages>(0);
     private Set<Developervalid> developervalids = new HashSet<Developervalid>(0);
     private Set<Developerhascomment> developerhascomments = new HashSet<Developerhascomment>(0);

    public Developer() {
    }

	
    public Developer(City city, String username, String developerFname, String password, String address, boolean state) {
        this.city = city;
        this.username = username;
        this.developerFname = developerFname;
        this.password = password;
        this.address = address;
        this.state = state;
    }
    public Developer(City city, Emailvarified emailvarified, String username, String developerFname, String developerMname, String developerLname, String password, String developerPhone, String developerMobile, String address, boolean state, Set<Delopercokie> delopercokies, Set<Application> applications, Set<Developerhaslanguages> developerhaslanguageses, Set<Developervalid> developervalids, Set<Developerhascomment> developerhascomments) {
       this.city = city;
       this.emailvarified = emailvarified;
       this.username = username;
       this.developerFname = developerFname;
       this.developerMname = developerMname;
       this.developerLname = developerLname;
       this.password = password;
       this.developerPhone = developerPhone;
       this.developerMobile = developerMobile;
       this.address = address;
       this.state = state;
       this.delopercokies = delopercokies;
       this.applications = applications;
       this.developerhaslanguageses = developerhaslanguageses;
       this.developervalids = developervalids;
       this.developerhascomments = developerhascomments;
    }
   
    public Integer getIdDeveloper() {
        return this.idDeveloper;
    }
    
    public void setIdDeveloper(Integer idDeveloper) {
        this.idDeveloper = idDeveloper;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Emailvarified getEmailvarified() {
        return this.emailvarified;
    }
    
    public void setEmailvarified(Emailvarified emailvarified) {
        this.emailvarified = emailvarified;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getDeveloperFname() {
        return this.developerFname;
    }
    
    public void setDeveloperFname(String developerFname) {
        this.developerFname = developerFname;
    }
    public String getDeveloperMname() {
        return this.developerMname;
    }
    
    public void setDeveloperMname(String developerMname) {
        this.developerMname = developerMname;
    }
    public String getDeveloperLname() {
        return this.developerLname;
    }
    
    public void setDeveloperLname(String developerLname) {
        this.developerLname = developerLname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDeveloperPhone() {
        return this.developerPhone;
    }
    
    public void setDeveloperPhone(String developerPhone) {
        this.developerPhone = developerPhone;
    }
    public String getDeveloperMobile() {
        return this.developerMobile;
    }
    
    public void setDeveloperMobile(String developerMobile) {
        this.developerMobile = developerMobile;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Delopercokie> getDelopercokies() {
        return this.delopercokies;
    }
    
    public void setDelopercokies(Set<Delopercokie> delopercokies) {
        this.delopercokies = delopercokies;
    }
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }
    public Set<Developerhaslanguages> getDeveloperhaslanguageses() {
        return this.developerhaslanguageses;
    }
    
    public void setDeveloperhaslanguageses(Set<Developerhaslanguages> developerhaslanguageses) {
        this.developerhaslanguageses = developerhaslanguageses;
    }
    public Set<Developervalid> getDevelopervalids() {
        return this.developervalids;
    }
    
    public void setDevelopervalids(Set<Developervalid> developervalids) {
        this.developervalids = developervalids;
    }
    public Set<Developerhascomment> getDeveloperhascomments() {
        return this.developerhascomments;
    }
    
    public void setDeveloperhascomments(Set<Developerhascomment> developerhascomments) {
        this.developerhascomments = developerhascomments;
    }




}


