package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Developervalid generated by hbm2java
 */
public class Developervalid  implements java.io.Serializable {


     private Integer idDeveloperValid;
     private Developer developer;
     private Staff staff;
     private Date developerValidDateAndTime;
     private boolean developerValidState;

    public Developervalid() {
    }

    public Developervalid(Developer developer, Staff staff, Date developerValidDateAndTime, boolean developerValidState) {
       this.developer = developer;
       this.staff = staff;
       this.developerValidDateAndTime = developerValidDateAndTime;
       this.developerValidState = developerValidState;
    }
   
    public Integer getIdDeveloperValid() {
        return this.idDeveloperValid;
    }
    
    public void setIdDeveloperValid(Integer idDeveloperValid) {
        this.idDeveloperValid = idDeveloperValid;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Date getDeveloperValidDateAndTime() {
        return this.developerValidDateAndTime;
    }
    
    public void setDeveloperValidDateAndTime(Date developerValidDateAndTime) {
        this.developerValidDateAndTime = developerValidDateAndTime;
    }
    public boolean isDeveloperValidState() {
        return this.developerValidState;
    }
    
    public void setDeveloperValidState(boolean developerValidState) {
        this.developerValidState = developerValidState;
    }




}


