package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private Staff staff;
     private Date loginDateAndTime;
     private Date logOutDateAndTime;

    public Login() {
    }

	
    public Login(Staff staff) {
        this.staff = staff;
    }
    public Login(Staff staff, Date loginDateAndTime, Date logOutDateAndTime) {
       this.staff = staff;
       this.loginDateAndTime = loginDateAndTime;
       this.logOutDateAndTime = logOutDateAndTime;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Date getLoginDateAndTime() {
        return this.loginDateAndTime;
    }
    
    public void setLoginDateAndTime(Date loginDateAndTime) {
        this.loginDateAndTime = loginDateAndTime;
    }
    public Date getLogOutDateAndTime() {
        return this.logOutDateAndTime;
    }
    
    public void setLogOutDateAndTime(Date logOutDateAndTime) {
        this.logOutDateAndTime = logOutDateAndTime;
    }




}


