package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer idStaff;
     private City city;
     private Emailvarified emailvarified;
     private Roles roles;
     private String staffFname;
     private String staffMname;
     private String staffLname;
     private String staffPassword;
     private String username;
     private Date staffRegDateAndTime;
     private String address;
     private boolean state;
     private Set<Staffcokie> staffcokies = new HashSet<Staffcokie>(0);
     private Set<Developervalid> developervalids = new HashSet<Developervalid>(0);
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Staffhassubmenu> staffhassubmenus = new HashSet<Staffhassubmenu>(0);
     private Set<Apphasstaffvalid> apphasstaffvalids = new HashSet<Apphasstaffvalid>(0);

    public Staff() {
    }

	
    public Staff(City city, Emailvarified emailvarified, Roles roles, String staffPassword, String username, Date staffRegDateAndTime, boolean state) {
        this.city = city;
        this.emailvarified = emailvarified;
        this.roles = roles;
        this.staffPassword = staffPassword;
        this.username = username;
        this.staffRegDateAndTime = staffRegDateAndTime;
        this.state = state;
    }
    public Staff(City city, Emailvarified emailvarified, Roles roles, String staffFname, String staffMname, String staffLname, String staffPassword, String username, Date staffRegDateAndTime, String address, boolean state, Set<Staffcokie> staffcokies, Set<Developervalid> developervalids, Set<Login> logins, Set<Staffhassubmenu> staffhassubmenus, Set<Apphasstaffvalid> apphasstaffvalids) {
       this.city = city;
       this.emailvarified = emailvarified;
       this.roles = roles;
       this.staffFname = staffFname;
       this.staffMname = staffMname;
       this.staffLname = staffLname;
       this.staffPassword = staffPassword;
       this.username = username;
       this.staffRegDateAndTime = staffRegDateAndTime;
       this.address = address;
       this.state = state;
       this.staffcokies = staffcokies;
       this.developervalids = developervalids;
       this.logins = logins;
       this.staffhassubmenus = staffhassubmenus;
       this.apphasstaffvalids = apphasstaffvalids;
    }
   
    public Integer getIdStaff() {
        return this.idStaff;
    }
    
    public void setIdStaff(Integer idStaff) {
        this.idStaff = idStaff;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Emailvarified getEmailvarified() {
        return this.emailvarified;
    }
    
    public void setEmailvarified(Emailvarified emailvarified) {
        this.emailvarified = emailvarified;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getStaffFname() {
        return this.staffFname;
    }
    
    public void setStaffFname(String staffFname) {
        this.staffFname = staffFname;
    }
    public String getStaffMname() {
        return this.staffMname;
    }
    
    public void setStaffMname(String staffMname) {
        this.staffMname = staffMname;
    }
    public String getStaffLname() {
        return this.staffLname;
    }
    
    public void setStaffLname(String staffLname) {
        this.staffLname = staffLname;
    }
    public String getStaffPassword() {
        return this.staffPassword;
    }
    
    public void setStaffPassword(String staffPassword) {
        this.staffPassword = staffPassword;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Date getStaffRegDateAndTime() {
        return this.staffRegDateAndTime;
    }
    
    public void setStaffRegDateAndTime(Date staffRegDateAndTime) {
        this.staffRegDateAndTime = staffRegDateAndTime;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Staffcokie> getStaffcokies() {
        return this.staffcokies;
    }
    
    public void setStaffcokies(Set<Staffcokie> staffcokies) {
        this.staffcokies = staffcokies;
    }
    public Set<Developervalid> getDevelopervalids() {
        return this.developervalids;
    }
    
    public void setDevelopervalids(Set<Developervalid> developervalids) {
        this.developervalids = developervalids;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<Staffhassubmenu> getStaffhassubmenus() {
        return this.staffhassubmenus;
    }
    
    public void setStaffhassubmenus(Set<Staffhassubmenu> staffhassubmenus) {
        this.staffhassubmenus = staffhassubmenus;
    }
    public Set<Apphasstaffvalid> getApphasstaffvalids() {
        return this.apphasstaffvalids;
    }
    
    public void setApphasstaffvalids(Set<Apphasstaffvalid> apphasstaffvalids) {
        this.apphasstaffvalids = apphasstaffvalids;
    }




}


