package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1



/**
 * Staffhassubmenu generated by hbm2java
 */
public class Staffhassubmenu  implements java.io.Serializable {


     private int idRolesHasSubmenu;
     private Staff staff;
     private Submenu submenu;

    public Staffhassubmenu() {
    }

    public Staffhassubmenu(int idRolesHasSubmenu, Staff staff, Submenu submenu) {
       this.idRolesHasSubmenu = idRolesHasSubmenu;
       this.staff = staff;
       this.submenu = submenu;
    }
   
    public int getIdRolesHasSubmenu() {
        return this.idRolesHasSubmenu;
    }
    
    public void setIdRolesHasSubmenu(int idRolesHasSubmenu) {
        this.idRolesHasSubmenu = idRolesHasSubmenu;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Submenu getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(Submenu submenu) {
        this.submenu = submenu;
    }




}


