package Entities;
// Generated Sep 9, 2016 6:59:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Submenu generated by hbm2java
 */
public class Submenu  implements java.io.Serializable {


     private int idsubmenu;
     private Menu menu;
     private String submenu;
     private String pageurl;
     private Set<Staffhassubmenu> staffhassubmenus = new HashSet<Staffhassubmenu>(0);

    public Submenu() {
    }

	
    public Submenu(int idsubmenu, Menu menu, String submenu) {
        this.idsubmenu = idsubmenu;
        this.menu = menu;
        this.submenu = submenu;
    }
    public Submenu(int idsubmenu, Menu menu, String submenu, String pageurl, Set<Staffhassubmenu> staffhassubmenus) {
       this.idsubmenu = idsubmenu;
       this.menu = menu;
       this.submenu = submenu;
       this.pageurl = pageurl;
       this.staffhassubmenus = staffhassubmenus;
    }
   
    public int getIdsubmenu() {
        return this.idsubmenu;
    }
    
    public void setIdsubmenu(int idsubmenu) {
        this.idsubmenu = idsubmenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(String submenu) {
        this.submenu = submenu;
    }
    public String getPageurl() {
        return this.pageurl;
    }
    
    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }
    public Set<Staffhassubmenu> getStaffhassubmenus() {
        return this.staffhassubmenus;
    }
    
    public void setStaffhassubmenus(Set<Staffhassubmenu> staffhassubmenus) {
        this.staffhassubmenus = staffhassubmenus;
    }




}


